### ISSUE TITLE
 Inquiry Regarding Sample Data and Radar Configuration

### ISSUE THREAD

**Issue by szgtvt** [smilelabkaist/Hawkeye#2]
I would like to express my sincere gratitude for sharing your code. It has been immensely helpful in my project.

I have a couple of questions regarding the sample data you provided. Could you please clarify the format of the sample data? Specifically, I am interested in understanding what each row and column in the data represent.

Additionally, would it be possible for you to share the corresponding configuration for the radar based on the sample data? This would greatly assist me in implementing your code effectively.

Thank you once again. I look forward to your response.

Best regards,
TvT

**Comment by KangMinBae** [comment]
The sample data follows the DemoRad data format from Analog Devices, with data D[0] as the chirp index. Details can be found at [this document](https://ez.analog.com/cfs-filesystemfile/__key/communityserver-discussions-components-files/333/FMCW_5F00_Basics_5F00_AN24_2D00_02_5F00_DemoRad_5F00_R_2D00_1_2D00_2_2D00_0_5F00_temp.pdf?_=637945201276290786).
